

//  export const spot_index_platts = ["MANDT", "ZSOURCEFEED", "ZSYMBOL", "ZBATE", "ZEFFDATE", "ZEFFTIME", "ZCREATE_DATE", "ZCREATE_TIME", "ZNETPRICE", "CORRECTED", "LATEST", "STATUS", "MDC_DESCR", "CURRENCY", "UOM", "CONVERT_FACTOR", "ZPRODUCT", "PRODUCT_GRADE", "DLVRY_REGION", "CONTRACT_TYPE", "HOLIDAY_SCHED", "QUOSRC", "QUOTYP", "QUOTNO", "INDEX_CODE"];

 export const spot_index_opis =  ["ZEFFDATE","ZEFFTIME","ZCREATE_DATETIME","ZNETPRICE","QUOSRC","QUOTYP","QUOTNO"];

//  export const rack_index_opis = ["MANDT","ZSOURCEFEED","ZCITY","ZSTATE","ZPRODUCT","Z_LHA","ZEFFDATE","ZEFFTIME","ZCREATE_DATETIME","ZLHA_DESCR","ZQUOTESTATUS","ZBRANDEDCODE","ZNETPRICE","ZRVP","ZPRODIND","ZPRODTYPE","ZDIESELBLEND","QUOSRC","QUOTYP","QUOTNO","ZMKT_CYCLE","ZFILENAME",	"ZBIOTYPE"];
// // export const rack_index_opis =  ["ZEFFDATE","ZEFFTIME","ZCREATE_DATETIME","ZNETPRICE","QUOSRC","QUOTYP","QUOTNO"];
//  export const rack_index_opis = ["ZCITY","ZSTATE","ZPRODUCT","Z_LHA","ZEFFDATE","ZEFFTIME","ZCREATE_DATETIME","ZLHA_DESCR","ZNETPRICE","ZRVP","ZPRODIND","ZPRODTYPE","QUOSRC","QUOTYP","QUOTNO"];

export const rack_index_opis =  ["ZCITY","ZSTATE","ZPRODUCT","Z_LHA","ZEFFDATE","ZEFFTIME","ZCREATE_DATETIME","ZNETPRICE","ZRVP","QUOSRC","QUOTYP","QUOTNO"];

export const spot_index_platts = ['ZEFFDATE', 'ZEFFTIME', 'ZCREATE_DATE',"ZCREATE_TIME",'ZNETPRICE','CURRENCY', 'UOM', 'QUOSRC', 'QUOTYP', 'QUOTNO']
